CREATE DATABASE Spendly
GO
USE Spendly
GO

CREATE TABLE [User](
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(150) NOT NULL,
	Username NVARCHAR(100) NOT NULL,
	PasswordHash NVARCHAR(200) NOT NULL,
	PasswordSalt NVARCHAR(200) NOT NULL,
	IsDeleted BIT NOT NULL DEFAULT 0

	CONSTRAINT UQ_User_Email UNIQUE (Email),
	CONSTRAINT UQ_User_Username UNIQUE (Username)
)
GO


CREATE TABLE [Group](
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	IsPersonal BIT NOT NULL DEFAULT 0,
	IsDeleted BIT NOT NULL DEFAULT 0
)
GO

CREATE TABLE Invitation(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Email NVARCHAR(150) NOT NULL,
	Token NVARCHAR(150) NOT NULL,
	ClaimedAt DATETIME NULL,
	ExpiredAt DATETIME NOT NULL,
	IsDeleted BIT NOT NULL DEFAULT 0,

	GroupId INT NOT NULL,
	CONSTRAINT FK_Invitation_Group FOREIGN KEY (GroupId) REFERENCES [Group](Id),
	CONSTRAINT UQ_Token UNIQUE (Token)
)
GO


--junction table USER <->GROUP 
CREATE TABLE UserGroup(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	UserId INT NOT NULL,
	GroupId INT NOT NULL,
	[Role] INT NOT NULL DEFAULT 0,
	
	CONSTRAINT FK_UserGroup_User FOREIGN KEY (UserId) REFERENCES [User](Id),
	CONSTRAINT FK_UserGroup_Group FOREIGN KEY (GroupId) REFERENCES [Group](Id),
	CONSTRAINT UQ_UserGroup UNIQUE (UserId, GroupId),

	JoinedAt DATETIME NOT NULL DEFAULT SYSDATETIME()
)
GO

CREATE TABLE CostType(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	GroupId INT NOT NULL,
	CONSTRAINT FK_CostType_Group  FOREIGN KEY (GroupId) REFERENCES [Group](Id)
)
GO

CREATE TABLE RevenueType(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	GroupId INT NOT NULL,
	CONSTRAINT FK_RevenueType_Group FOREIGN KEY (GroupId) REFERENCES [Group](Id)

)
GO

CREATE TABLE Budget(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Amount DECIMAL(18,2) NOT NULL,
	[Year] INT NOT NULL,
	[Month] INT NOT NULL,
	IsDeleted BIT NOT NULL DEFAULT 0,

	UserGroupId INT NOT NULL,
	Currency INT NOT NULL,

    CONSTRAINT FK_Budget_UserGroup FOREIGN KEY (UserGroupId) REFERENCES UserGroup(Id),
	CONSTRAINT UQ_Budget UNIQUE (UserGroupId, [Month], [Year])
)
GO


CREATE TABLE Cost(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Amount DECIMAL(18,2) NOT NULL,
	TransactionDate DATETIME NOT NULL DEFAULT SYSDATETIME(),
	Notes NVARCHAR(MAX) NULL,
	IsDeleted BIT NOT NULL DEFAULT 0,

	UserId INT NOT NULL,
	Currency INT NOT NULL,
	CostTypeId INT NOT NULL,
	GroupId INT NOT NULL,

	CONSTRAINT FK_Cost_User FOREIGN KEY (UserId) REFERENCES [User](Id),
	CONSTRAINT FK_Cost_CostType FOREIGN KEY (CostTypeId) REFERENCES CostType(Id),
	CONSTRAINT FK_Cost_Group FOREIGN KEY (GroupId) REFERENCES [Group](Id)
)
GO


CREATE TABLE Revenue(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Amount DECIMAL(18,2) NOT NULL,
	TransactionDate DATETIME NOT NULL DEFAULT SYSDATETIME(),
	Notes NVARCHAR(MAX) NULL,
	IsDeleted BIT NOT NULL DEFAULT 0,

	UserId INT NOT NULL,
	Currency INT NOT NULL,
	RevenueTypeId INT NOT NULL,
	GroupId INT NOT NULL,

	CONSTRAINT FK_Revenue_User FOREIGN KEY (UserId) REFERENCES [User](Id),
	CONSTRAINT FK_Revenue_RevenueType FOREIGN KEY (RevenueTypeId) REFERENCES RevenueType(Id),
	CONSTRAINT FK_Revenue_Group FOREIGN KEY (GroupId) REFERENCES [Group](Id)
)
GO